version: '3.9'
services:
  encryptor:
    container_name: encryptor
    build: ./encryptor
    ports:
      - '8080:8080'
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      start_period: 3s
      interval: 2s
      timeout: 3s
      retries: 10

  k6:
    container_name: k6
    image: grafana/k6
    entrypoint: k6 run
    command: LoadTest.js
    working_dir: /workspace
    volumes:
      - ./k6:/workspace
    depends_on:
      encryptor:
        condition: service_healthy
